### ISSUE TITLE
grunt-cmd-concat合并任务问题

### ISSUE THREAD

**Issue by hpl934n** [twinstony/seajs-grunt-build#3]
grunt-cmd-transport任务产生的类库目录为：
gallery
|—lib
     —jquery
     —zepto
grunt-cmd-transport任务产生的业务模块和自定义模块目录为：
.build
|—app                              业务模块
    —login
|—plugins                          自定义模块
    —dialog
    —form
    —touch
    —validForm
在使用grunt-cmd-concat任务进行模块和并后，模块中对jquery模块依赖丢失。模块合并的写法为
concat : {
            options : {
                paths : ['.'],
                include : 'relative'
            },

```
        plugins : {
            files : [
                {
                    expand : true,
                    cwd : '.build/',
                    src : ['script/plugins/**/*.js'],
                    dest : 'dist/',
                    ext : '.js'
                }
            ]
        },

        app : {
            options : {
                include : 'all'
            },

            files : [
                {
                    expand : true,
                    cwd : '.build/',
                    src : ['script/app/**/*.js'],
                    dest : 'dist/',
                    ext : '.js'
                }
            ]
        }
    }
```

请问哈，这是怎么回事？

**Comment by twinstony** [comment]
log是显示无法找到模块jquery吗?
如果是的话,检查下package.json中的spm->alias->jquery的路径,是否与本地环境一致.八成是这里的配置不一样,找不到jquery了.

**Comment by hpl934n** [comment]
不是合并任务时找不到jquery模块，生成cmd模块时有模块依赖，合并任务后模块里面针对jquery模块依赖丢失了。找到问题原因了，是jquery文件名中带有点号（“.”）版本标识影响。去掉jquery文件名中的版本号就OK了。还是非常感谢 twinstony能够抽空帮忙解答，谢谢！

**Comment by twinstony** [comment]
close
