### ISSUE TITLE
压缩css进来出了问题

### ISSUE THREAD

**Issue by hguankei** [twinstony/seajs-grunt-build#4]
seajs.importStyle(".engine_list{background:#dbdee2}.engine_list_box .btn_analysis{float:left}")

css会变成这种形式压缩进来

可是console报错

Uncaught TypeError: Object #<Object> has no method 'importStyle' 

请教这是什么问题，谢谢

**Comment by hguankei** [comment]
明白了，我没引入style插件

**Comment by hodorwang** [comment]
引入了还是报这个错，为什么呢

**Comment by hodorwang** [comment]
文件加载到了，没执行里面的回调

**Comment by hodorwang** [comment]
http://jsfiddle.net/EWq2R/
