### ISSUE TITLE
全部编译放在一个Gruntfile.js文件有点乱

### ISSUE THREAD

**Issue by shrek82** [twinstony/seajs-grunt-build#5]
案例中的疑问，如果有10个或更多个模块时，将每个模块的编译配置加入到Gruntfile.js，多了之后，Gruntfile.js是不是有点乱了，package.json里version和name也会使各个模块版本号都不能独立，可如果每一个模块（一个目录）一个Gruntfile.js和package.json和node_modules，模块体积有比较大的和不易升级需要的组件，不知道如何解决才好。

**Comment by twinstony** [comment]
你所说的模块是什么意思？module吗？
如果是module的话，不需要单独在Gruntfile.js中处理。
本例中只是演示了一个多项目共存的一种情况。
